### ISSUE TITLE
extract raster dataset

### ISSUE THREAD

**Issue by egouden** [wradlib/wradlib#341] opened 2019-06-03 13:39 UTC
By default the function extract_raster_dataset returns pixel edge coordinates with shape (nrows+1,ncols+1,2).
This is inconsistent with the documentation.
What about the function returning pixel center coordinates as would many users expect and add a boolean parameter "edge" for this particular usage?

**Comment by kmuehlbauer** [comment] 2019-06-03 15:42
@egouden Agreed! This can be done like here:  https://docs.wradlib.org/en/stable/generated/wradlib.georef.raster.read_gdal_coordinates.html#wradlib.georef.raster.read_gdal_coordinates. PR welcome.

**Comment by egouden** [comment] 2019-06-07 13:39
PR in preparation with several improvements
I need some gdal compatible radar data for testing.
See my PR in wradlib-data.

**Comment by kmuehlbauer** [comment] 2019-06-07 13:40
@egouden Just merged the belgian radar data over in wradlib-data!

**Comment by kmuehlbauer** [comment] 2019-08-30 06:46
@egouden Let's discuss the issue here to not clutter the PR #376 with possibly unrelated stuff.

I went trough the code, again. 

Here are my findings/suggestions for further discussion:

General
----------
- [pixel_to_map3d](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L97) was intended to fetch the srtm data (at least, there is this note in the docstring), it will be deprecated and removed from the API, `get_raster_elevation` (see #376) will be introduced for that functionality.
- [extract_raster_dataset](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L309) should be the one and only API function for raster dataset extraction. It should be extended via keywords to return data, coords and proj as requested. 
- all other functions ([read_gdal_coordinates](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L127), [read_gdal_values](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L185), [read_gdal_projection](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L160), [pixel_coordinates](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L32), [pixel_to_map](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L64)) should be revised and made private

Alignment
-------------
- [extract_raster_dataset](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/georef/raster.py#L309) should output the coordinates via keyword `mode="edges"` using pixel edge coordinates and via `mode="centers"` using pixel center coordinates (we can discuss naming etc)
- all involved functions needs revision to comply to this
- `edges` means UPPER LEFT CORNER or LOWER LEFT CORNER pixel coordinates (based on origin) with shape of `(nrows, ncols, 2)`
- `centers` means  CENTER pixel coordinates with shape of `(nrows, ncols, 2)`

If the implementation breaks the API (which it will likely do), we should try to issue deprecation warnings, but I'm also open for moving to wradlib v2.0 to avoid breaking semver.

**Comment by egouden** [comment] 2019-09-02 14:48
I tend to agree with the analysis.
See the updated pull request.

**Closed** 2019-10-09 14:37 UTC
